# Generated by Django 2.1.7 on 2019-02-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_auto_20190218_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Programming_Languages',
            field=models.CharField(choices=[('C', 'C++'), ('JAVA', 'Core JAVA'), ('Python', 'Advanced Python Django'), ('C#', 'C Sharp'), ('.net', 'ASP.net'), ('Mag', 'Magento2'), ('sft', 'Swift'), ('Web', 'HTML CSS'), ('net', 'networking')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
