# Generated by Django 2.1.7 on 2019-02-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_employee_programming_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Country',
            field=models.CharField(choices=[('my', 'India'), ('out', 'other')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
