# Generated by Django 2.1.7 on 2019-02-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_auto_20190219_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Country',
            field=models.CharField(choices=[('India', 'India'), ('out', 'other')], max_length=2),
        ),
    ]
