# Generated by Django 2.1.7 on 2019-02-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0008_auto_20190220_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Country',
            field=models.CharField(choices=[('In', 'India'), ('out', 'other')], max_length=2),
        ),
    ]
