# Generated by Django 2.1.7 on 2019-02-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0011_auto_20190220_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Country',
            field=models.CharField(choices=[('india', 'India'), ('out', 'other')], max_length=10),
        ),
    ]
