# Generated by Django 2.1.7 on 2019-02-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0012_auto_20190220_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Country',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Programming_Languages',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
