# Generated by Django 2.1.7 on 2019-02-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0013_auto_20190221_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Country',
            field=models.CharField(choices=[('india', 'India'), ('out', 'other')], default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='Programming_Languages',
            field=models.CharField(choices=[('C', 'C++'), ('JAVA', 'Core JAVA'), ('Python', 'Advanced Python Django'), ('C#', 'C Sharp'), ('.net', 'ASP.net'), ('Mag', 'Magento2'), ('sft', 'Swift'), ('Web', 'HTML CSS'), ('net', 'networking')], default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
