# Generated by Django 2.1.7 on 2019-02-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0014_auto_20190221_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Date_of_Birth',
            field=models.DateField(null=True),
        ),
    ]
