# Generated by Django 2.1.7 on 2019-02-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0015_auto_20190227_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Image',
            field=models.ImageField(blank=True, default='media/default.jpg', upload_to='profile_pics'),
        ),
    ]
