# Generated by Django 2.1.7 on 2019-02-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0017_auto_20190228_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='File',
            field=models.FileField(null=True, upload_to='get_file'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
