# Generated by Django 2.1.7 on 2019-03-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0018_auto_20190228_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Country',
            field=models.CharField(choices=[('India', 'India'), ('Other', 'Other')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='get_file'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Programming_Languages',
            field=models.CharField(choices=[('C++', 'C++'), ('JAVA', 'Core JAVA'), ('Python', 'Advanced Python Django'), ('C Sharp', 'C Sharp'), ('ASP.net', 'ASP.net'), ('Magento', 'Magento'), ('Swift', 'Swift'), ('HTML CSS', 'HTML CSS'), ('Networking', 'Networking')], max_length=1000),
        ),
    ]
